version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: budget-app-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: budget_db
    ports:
      - "5432:5432"
    volumes:
      - budget-app-postgres-data:/var/lib/postgresql/data

volumes:
  budget-app-postgres-data:
